/*
 * nfc_mfc_dict_ui_draw_extracted.c -- GENERATED by extract_mfc_dict_ui.py.
 * DO NOT EDIT BY HAND -- re-run the generator instead. See that script's
 * own header comment for exactly which real source ranges each part below
 * came from and why.
 *
 * Every non-comment line below is a byte-exact copy of a real, currently-
 * checked-out line from m1_csrc/m1_nfc.c or m1_csrc/m1_display.c (plus a
 * handful of macro/typedef/enum lines from their real, portable headers).
 * Neither .c file was ever modified to produce this.
 */

/* ---- macros, verbatim from m1_display.h / m1_lcd.h / m1_nfc.c ---- */
#define M1_DISP_DRAW_COLOR_BG		0
#define M1_DISP_DRAW_COLOR_TXT		1
#define M1_DISP_MAIN_MENU_FONT_N		u8g2_font_resoledmedium_tr // 5x10 //u8g2_font_6x10_tf //, , u8g2_font_medsans_tr: clear font
#define M1_DISP_MAIN_MENU_FONT_B		u8g2_font_helvB08_tf
#define M1_DISP_SUB_MENU_FONT_N			u8g2_font_resoledmedium_tr // Nokia removed; unified with the main-menu font
#define M1_DISP_SUB_MENU_FONT_B			u8g2_font_squeezed_b7_tr //, u8g2_font_ncenB08_tf: slightly wide bold,
#define M1_DISP_FUNC_MENU_FONT_N		u8g2_font_spleen5x8_mf // u8g2_font_nine_by_five_nbp_tf // u8g2_font_miranda_nbp_tf // u8g2_font_5x8_tf
#define M1_MAIN_LOGO_FONT_1B			u8g2_font_Pixellari_tu // 10 pixel
#define M1_LCD_DISPLAY_WIDTH	128
#define M1_LCD_DISPLAY_HEIGHT	64
#define NFC_HEXCELL_W   6      /* fixed hex cell width (px) - alignment w/o mono font */
#define NFC_HEXGRP_GAP  3      /* extra gap between 4-digit (2-byte) groups */
#define NFC_FONT_STD    M1_DISP_MAIN_MENU_FONT_N   /* u8g2_font_resoledmedium_tr */
#define NFC_FONT_EMPH   M1_DISP_MAIN_MENU_FONT_B   /* u8g2_font_helvB08_tf       */

/* ---- m1_menu.h / m1_system.h types, verbatim (S_M1_Menu_t's own
 * xkey_handler field type + the menu-update direction enum
 * m1_gui_submenu_update() below is written against) ---- */
#define MENU_TITLE_LEN          30
#define SUB_MENU_ITEMS_MAX      10
#define SUB_MENU_LEVEL_MAX      5
typedef enum {
	BUTTON_EVENT_IDLE = 0x00,
	BUTTON_EVENT_CLICK,
	BUTTON_EVENT_DBCLICK,
	BUTTON_EVENT_LCLICK
} S_M1_Key_Event;
typedef struct S_M1_Menu
{
	char title[MENU_TITLE_LEN];
    void (*sub_func)(void); // Main subfunction
    void (*deinit_func)(void); // This subfunction is called before this menu becomes inactive
    void (*xkey_handler)(S_M1_Key_Event event, uint8_t button_id, uint8_t sel_item); // Extra key handling subfunc, if any
    uint8_t num_submenu_items;
    uint8_t reserved;
    const uint8_t *icon_ptr; // Pointer to image buffer for the icon, if any
    // Pointer to the gui update function for this menu item if needed
    void (*gui_menu_update)(const struct S_M1_Menu *phmenu, uint8_t sel_item);
    struct S_M1_Menu *submenu[SUB_MENU_ITEMS_MAX];
} S_M1_Menu_t;
typedef enum
{
	MENU_UPDATE_NONE = 0, // No display update
	MENU_UPDATE_MOVE_UP, // Menu moves up
	MENU_UPDATE_MOVE_DOWN, // Menu moves down
	MENU_UPDATE_RESET, // Display new menu or sub-menu
	MENU_UPDATE_RESTORE, // Display previous menu
	MENU_UPDATE_REFRESH, // Refresh current menu after a function completes
	MENU_UPDATE_INIT, // Menu initialized
	X_MENU_UPDATE_INIT, // Used for the extra menu of a menu item
	X_MENU_UPDATE_MOVE_UP,
	X_MENU_UPDATE_MOVE_DOWN,
	X_MENU_UPDATE_RESET,
	X_MENU_UPDATE_RESTORE,
	X_MENU_UPDATE_REFRESH
} S_M1_Menu_Update_t;

/* ---- nfc_draw_hex_cells() (m1_nfc.c), verbatim ---- */
static uint8_t nfc_draw_hex_cells(uint8_t x0, uint8_t y, const uint8_t *bytes, uint8_t n)
{
    static const char HEXD[] = "0123456789ABCDEF";
    uint8_t x = x0;
    for (uint8_t i = 0; i < n; i++)
    {
        uint8_t grp = (uint8_t)(i / 2);   /* 2 bytes = one 4-digit group */
        uint8_t cx  = (uint8_t)(x0 + i * 2 * NFC_HEXCELL_W + grp * NFC_HEXGRP_GAP);
        char hi[2] = { HEXD[(bytes[i] >> 4) & 0x0F], 0 };
        char lo[2] = { HEXD[bytes[i] & 0x0F], 0 };
        uint8_t wh = (uint8_t)u8g2_GetStrWidth(&m1_u8g2, hi);
        uint8_t wl = (uint8_t)u8g2_GetStrWidth(&m1_u8g2, lo);
        u8g2_DrawStr(&m1_u8g2, cx + (NFC_HEXCELL_W - wh) / 2, y, hi);
        u8g2_DrawStr(&m1_u8g2, cx + NFC_HEXCELL_W + (NFC_HEXCELL_W - wl) / 2, y, lo);
        x = (uint8_t)(cx + 2 * NFC_HEXCELL_W);
    }
    return x;
}

/* ---- s_ndef_state (m1_nfc.c), verbatim declaration ---- */
static uint8_t s_ndef_state = 0xFF;

/* ---- MFC dictionary-progress totals cache (m1_nfc.c), verbatim ---- */
static uint32_t s_mfc_dict_total_builtin;
static uint32_t s_mfc_dict_total_user;
static uint32_t s_mfc_dict_total_system;
static bool     s_mfc_dict_totals_computed = false;

static void nfc_mfc_dict_totals_ensure(void)
{
	if (s_mfc_dict_totals_computed) return;

	const char           *user_paths[2], *sys_paths[2];
	mfc_key_source_cfg_t  cfgs[2];
	m1_mfc_build_key_sources(cfgs, user_paths, sys_paths);
	s_mfc_dict_total_builtin = (uint32_t)cfgs[1].builtin_n;
	s_mfc_dict_total_user    = mfc_key_source_count(&cfgs[0], 1).count;
	mfc_key_source_cfg_t sys_file_only = cfgs[1];
	sys_file_only.builtin = NULL; sys_file_only.builtin_n = 0;
	s_mfc_dict_total_system = mfc_key_source_count(&sys_file_only, 1).count;

	s_mfc_dict_totals_computed = true;
}

static void nfc_mfc_dict_totals_invalidate(void)
{
	s_mfc_dict_totals_computed = false;
}

/* ---- Dictionary-progress renderer family (m1_nfc.c), verbatim ---- */
static void nfc_mfc_progress_bar_draw(uint8_t x, uint8_t y, uint8_t w, uint8_t h,
                                      uint32_t current, uint32_t total)
{
	char     line[24];
	uint8_t  fill_w;

	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
	u8g2_DrawFrame(&m1_u8g2, x, y, w, h);

	if (total == 0U) {
		fill_w = 0U;   /* zero-total-safe: an empty, un-filled bar, never a divide-by-zero */
	} else {
		uint32_t c = (current > total) ? total : current;   /* clamp at 100% */
		fill_w = (uint8_t)(((uint32_t)(w - 2U) * c) / total);
	}
	if (fill_w > 0U) u8g2_DrawBox(&m1_u8g2, (uint8_t)(x + 1), (uint8_t)(y + 1), fill_w, (uint8_t)(h - 2U));

	/* A genuinely-zero current is shown as 1 so the
	 * bar never reads as stuck/inert on the very first candidate. */
	snprintf(line, sizeof(line), "%lu/%lu",
	         (unsigned long)((current == 0U) ? 1U : current), (unsigned long)total);
	u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);
	uint8_t text_w = (uint8_t)u8g2_GetStrWidth(&m1_u8g2, line);
	uint8_t text_x = (uint8_t)(x + ((w > text_w) ? ((w - text_w) / 2U) : 0U));
	uint8_t text_y = (uint8_t)(y + h - 2U);
	uint8_t fill_x1 = (uint8_t)(x + 1U + fill_w);

	if (fill_w > 0U) {
		u8g2_SetClipWindow(&m1_u8g2, x, y, fill_x1, (uint8_t)(y + h));
		u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_BG);
		u8g2_DrawStr(&m1_u8g2, text_x, text_y, line);
	}
	u8g2_SetClipWindow(&m1_u8g2, fill_x1, y, (uint8_t)(x + w), (uint8_t)(y + h));
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
	u8g2_DrawStr(&m1_u8g2, text_x, text_y, line);
	u8g2_SetMaxClipWindow(&m1_u8g2);   /* restore -- every other draw call in this file assumes full-screen clipping */
}

static void nfc_mfc_dict_progress_draw(void)
{
	nfc_mfc_scan_t       *sc = nfc_ctx_get_mfc_scan();
	const nfc_mfc_info_t *mc = nfc_ctx_get_mfc_info();
	char line[28];
	unsigned kt = (mc->keys_total > 0U) ? mc->keys_total : 32U;
	unsigned st = (mc->sectors_total > 0U) ? mc->sectors_total : 16U;

	nfc_mfc_dict_totals_ensure();

	/* Header: the truthful active source -- exactly the three real M1
	 * origins, never collapsed or invented. Matches the header-
	 * is-the-active-dictionary convention. "MF Classic " is dropped from
	 * the on-screen label (kept in code comments/docs) because at
	 * NFC_FONT_EMPH the full "MF Classic System Dictionary" measures
	 * 149px -- wider than the 126px usable width -- and clips; this screen
	 * is only ever reached for M1NFC_FAM_CLASSIC, so the prefix carries no
	 * information the context doesn't already give. */
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
	u8g2_SetFont(&m1_u8g2, NFC_FONT_EMPH);
	u8g2_DrawStr(&m1_u8g2, 2, 9,
	    (sc->cur_source == NFC_SCAN_SRC_USER)    ? "User Dictionary" :
	    (sc->cur_source == NFC_SCAN_SRC_BUILTIN) ? "Built-in Keys"   :
	                                               "System Dictionary");
	u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);

	snprintf(line, sizeof(line), "Unlocking sector: %u", (unsigned)sc->cur_sector);
	u8g2_DrawStr(&m1_u8g2, 2, 19, line);

	uint32_t src_total =
	    (sc->cur_source == NFC_SCAN_SRC_USER)    ? s_mfc_dict_total_user :
	    (sc->cur_source == NFC_SCAN_SRC_BUILTIN) ? s_mfc_dict_total_builtin :
	                                               s_mfc_dict_total_system;
	nfc_mfc_progress_bar_draw(2, 22, 124, 10, sc->src_tried, src_total);

	snprintf(line, sizeof(line), "Keys found: %u/%u", (unsigned)sc->found, kt);
	u8g2_DrawStr(&m1_u8g2, 2, 42, line);
	snprintf(line, sizeof(line), "Sectors Read: %u/%u", (unsigned)sc->sectors_acc, st);
	u8g2_DrawStr(&m1_u8g2, 2, 51, line);

	/* Footer: CENTER + Skip, full-width -- matches the established M1
	 * single-control footer convention (target_10x10 icon + label). */
	u8g2_DrawBox(&m1_u8g2, 0, 52, 128, 12);
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_BG);
	u8g2_DrawXBMP(&m1_u8g2, 2, 53, 10, 10, target_10x10);
	u8g2_SetFont(&m1_u8g2, M1_DISP_FUNC_MENU_FONT_N);
	u8g2_DrawStr(&m1_u8g2, 15, 61, "Skip");
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
}

static void nfc_mfc_lost_tag_draw(void)
{
	/* Lost-tag text: the
	 * progress UI is hidden, but Skip stays available -- the user is never
	 * stuck with no way out just because the card wandered off. */
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
	u8g2_SetFont(&m1_u8g2, NFC_FONT_EMPH);
	u8g2_DrawStr(&m1_u8g2, (uint8_t)((128 - u8g2_GetStrWidth(&m1_u8g2, "Lost the tag!")) / 2U), 13, "Lost the tag!");
	u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);
	u8g2_DrawStr(&m1_u8g2, 2, 30, "Make sure the tag is");
	u8g2_DrawStr(&m1_u8g2, 2, 40, "positioned correctly.");

	u8g2_DrawBox(&m1_u8g2, 0, 52, 128, 12);
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_BG);
	u8g2_DrawXBMP(&m1_u8g2, 2, 53, 10, 10, target_10x10);
	u8g2_SetFont(&m1_u8g2, M1_DISP_FUNC_MENU_FONT_N);
	u8g2_DrawStr(&m1_u8g2, 15, 61, "Skip");
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
}

static void nfc_mfc_exit_confirm_draw(void)
{
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
	u8g2_SetFont(&m1_u8g2, NFC_FONT_EMPH);
	u8g2_DrawStr(&m1_u8g2, (uint8_t)((128 - u8g2_GetStrWidth(&m1_u8g2, "Exit to NFC Menu?")) / 2U), 13,
	            "Exit to NFC Menu?");
	u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);
	/* "All unsaved data will be lost" does not fit NFC_FONT_STD's width in
	 * one line -- wrapped across two lines, left-aligned, matching the same
	 * convention nfc_mfc_lost_tag_draw()'s own two-line body already uses. */
	u8g2_DrawStr(&m1_u8g2, 2, 30, "All unsaved data");
	u8g2_DrawStr(&m1_u8g2, 2, 40, "will be lost");

	/* LEFT = Exit, RIGHT = Stay -- matching the left/right
	 * placement exactly, and this file's own established split-footer
	 * convention (arrowleft/arrowright, e.g. the read-result Retry/More bar). */
	u8g2_DrawXBMP(&m1_u8g2, 1, 53, 8, 8, arrowleft_8x8);
	u8g2_DrawStr(&m1_u8g2, 11, 61, "Exit");
	u8g2_DrawStr(&m1_u8g2, 117 - (uint8_t)u8g2_GetStrWidth(&m1_u8g2, "Stay"), 61, "Stay");
	u8g2_DrawXBMP(&m1_u8g2, 119, 53, 8, 8, arrowright_8x8);
}

static void nfc_mfc_find_keys_draw(void)
{
	nfc_mfc_scan_t        *sc = nfc_ctx_get_mfc_scan();
	const nfc_mfc_info_t  *mc = nfc_ctx_get_mfc_info();
	char line[28];
	unsigned kt = (mc->keys_total > 0U) ? mc->keys_total : 32U;
	unsigned st = (mc->sectors_total > 0U) ? mc->sectors_total : 16U;

	if (sc->state == NFC_SCAN_RUNNING) {
		nfc_mfc_dict_progress_draw();   /* shared renderer -- see above */
		return;
	}
	if (sc->state == NFC_SCAN_CARD_LOST) {
		nfc_mfc_lost_tag_draw();        /* shared renderer -- live/resumable, not terminal */
		return;
	}

	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
	u8g2_SetFont(&m1_u8g2, NFC_FONT_EMPH);
	u8g2_DrawStr(&m1_u8g2, 2, 9, "Finding Keys");
	u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);

	if (sc->state == NFC_SCAN_WAIT_CARD) {
		u8g2_DrawStr(&m1_u8g2, 2, 34, "Present the same card...");
		return;
	}
	if (sc->state == NFC_SCAN_FAIL) {
		u8g2_DrawStr(&m1_u8g2, 2, 34, "Not a MFC 1K/4K card");
		return;
	}
	if (sc->state == NFC_SCAN_IDENTITY_MISMATCH) {
		/* Truthful: this refusal never touches the original partial
		 * result (nfc_mfc_find_keys_run()), so say so plainly. */
		u8g2_DrawStr(&m1_u8g2, 2, 34, "Different card presented");
		u8g2_DrawStr(&m1_u8g2, 2, 45, "Progress preserved");
		return;
	}

	/* Terminal: DONE / STOPPED. */
	u8g2_DrawStr(&m1_u8g2, 2, 22, (sc->state == NFC_SCAN_DONE) ? "Complete" : "Stopped");
	snprintf(line, sizeof(line), "Found %u/%u", (unsigned)sc->found, kt);
	u8g2_DrawStr(&m1_u8g2, 2, 33, line);
	snprintf(line, sizeof(line), "Sectors %u/%u", (unsigned)sc->sectors_acc, st);
	u8g2_DrawStr(&m1_u8g2, 2, 44, line);
	u8g2_DrawStr(&m1_u8g2, 2, 61, "BACK to continue");
}

/* ---- Action-menu assembly (m1_nfc.c), verbatim ---- */
typedef enum {
    NFC_EMU_HIDE = 0,
    NFC_EMU_UID,
    NFC_EMU_FULL
} nfc_emu_cap_t;

typedef enum {
    NFC_ACT_SAVE = 0,
    NFC_ACT_EMULATE,
    NFC_ACT_WRITE,
    NFC_ACT_INFO,
    NFC_ACT_EDIT_UID,
    NFC_ACT_RENAME,
    NFC_ACT_DELETE,
    NFC_ACT_FIND_KEYS,   /* Find Missing Keys: dictionary-phase continuation of a partial MFC read */
    NFC_ACT_UNLOCK
} nfc_menu_action_t;

#define NFC_MENU_MAX_ITEMS   7

static nfc_emu_cap_t nfc_emu_menu(nfc_run_ctx_t *c)
{
    if (!c || c->head.uid_len == 0) return NFC_EMU_HIDE;

    switch (c->head.family) {
        case M1NFC_FAM_ULTRALIGHT:   /* Type 2 / NTAG        ("Emulate")              */
            return NFC_EMU_FULL;

        case M1NFC_FAM_CLASSIC:      /* Classic + generic NFC-A ("Emulate")           */
#if defined(M1_MFC_RAW_EMULATION)
            /* Do not offer an action guaranteed to refuse: pre-check the same
             * production eligibility gate nfc_emulate_gui_create() enforces
             * before RF starts (1K only, 4-byte UID, every block AND every
             * key known, UID/block-0/BCC consistent -- see
             * m1_mfc_emu_image.h) so a partial read or an unsupported 4K
             * card never shows "Emulate" only to reject it after the user
             * has already committed to the action. Read-only: builds and
             * discards a throwaway snapshot, no nfc_ctx side effects. */
            {
                m1_mfc_emu_image_t img;
                if (m1_mfc_emu_image_build(&img) != M1_MFC_EMU_OK) return NFC_EMU_HIDE;
            }
#endif
            return NFC_EMU_FULL;

        case M1NFC_FAM_DESFIRE:      /* ISO14443-4A          ("Emulate UID")          */
            return NFC_EMU_UID;

        case M1NFC_FAM_15693:        /* NFC-V:  emulation not offered this stage */
        case M1NFC_FAM_ST25TB:       /* NFC-B:  emulation not offered this stage */
        default:
            return NFC_EMU_HIDE;
    }
}

static bool nfc_can_write_ntag21x(nfc_run_ctx_t *c)
{
    if (!c || c->head.family != M1NFC_FAM_ULTRALIGHT) return false;
    switch (nfc_ctx_get_t2t_variant()) {
        case M1NFC_T2TVAR_UL:        /* Original Ultralight        */
        case M1NFC_T2TVAR_NTAG203:   /* NTAG203                    */
        case M1NFC_T2TVAR_ULC:       /* Ultralight C               */
        case M1NFC_T2TVAR_UL11:      /* EV1 MF0UL11                */
        case M1NFC_T2TVAR_UL21:      /* EV1 MF0UL21                */
        case M1NFC_T2TVAR_NTAG213:
        case M1NFC_T2TVAR_NTAG215:
        case M1NFC_T2TVAR_NTAG216:
            return true;
        default:
            return false;
    }
}

static bool nfc_can_write_mfc(nfc_run_ctx_t *c)
{
    if (!c || c->head.family != M1NFC_FAM_CLASSIC) return false;
    const nfc_mfc_info_t *mc = nfc_ctx_get_mfc_info();
    return (mc && mc->valid &&
            ((mc->type == M1NFC_MFCTYPE_1K) || (mc->type == M1NFC_MFCTYPE_4K)) &&
            mfc_action_eligibility(mc->outcome).emulate_write_allowed);
}

static bool nfc_can_unlock(nfc_run_ctx_t *c)
{
    if (!c || c->head.family != M1NFC_FAM_ULTRALIGHT) return false;
    switch (nfc_ctx_get_t2t_variant()) {
        case M1NFC_T2TVAR_UL11:
        case M1NFC_T2TVAR_NTAG213:
        case M1NFC_T2TVAR_NTAG215:
        case M1NFC_T2TVAR_NTAG216:
            break;
        default:
            return false;
    }
    uint8_t auth0 = 0xFFU;
    if (nfc_ctx_get_t2t_auth0(&auth0) && (auth0 != 0xFFU)) { return true; }
    return nfc_ctx_get_t2t_protection_suspected(NULL);
}

static uint8_t nfc_build_action_menu(const char *labels[NFC_MENU_MAX_ITEMS],
                                     uint8_t      actions[NFC_MENU_MAX_ITEMS])
{
    nfc_run_ctx_t *c = nfc_ctx_get();
    uint8_t n = 0;
    bool is_load_file = (c && c->file.source_kind == LOAD_FILE);
    bool is_st25tb    = (c && c->head.family == M1NFC_FAM_ST25TB);
    nfc_emu_cap_t emu = nfc_emu_menu(c);

    if (is_load_file) {
        /* Loaded file: already persisted, so no Save. */
        if (emu == NFC_EMU_UID)           { labels[n] = "Emulate UID"; actions[n++] = NFC_ACT_EMULATE; }
        else if (emu == NFC_EMU_FULL) { labels[n] = "Emulate";     actions[n++] = NFC_ACT_EMULATE; }
        if (nfc_can_unlock(c))                 { labels[n] = "Unlock";      actions[n++] = NFC_ACT_UNLOCK; }
        labels[n] = "Edit UID"; actions[n++] = NFC_ACT_EDIT_UID;
        labels[n] = "Info";     actions[n++] = NFC_ACT_INFO;
        labels[n] = "Rename";   actions[n++] = NFC_ACT_RENAME;
        labels[n] = "Delete";   actions[n++] = NFC_ACT_DELETE;
        return n;
    }

    /* LIVE card. For MIFARE Classic specifically, Save/Info follow the
     * outcome classifier (mfc_result.h) rather than the unconditional rule
     * every other live family still uses -- a FAILED/CANCELLED MFC read has
     * nothing worth saving or showing, and a PARTIAL one is truthfully
     * labeled "Save Partial", never plain "Save". Other families are
     * unaffected: they have no nfc_mfc_info_t.outcome concept at all. */
    bool is_mfc = (c && c->head.family == M1NFC_FAM_CLASSIC);
    mfc_action_eligibility_t mfc_elig;
    mfc_elig.save = false; mfc_elig.save_partial = false; mfc_elig.info = false;
    mfc_elig.try_again = false; mfc_elig.find_missing_keys = false; mfc_elig.emulate_write_allowed = false;
    if (is_mfc) {
        const nfc_mfc_info_t *mc = nfc_ctx_get_mfc_info();
        mfc_elig = mfc_action_eligibility(mc ? mc->outcome : MFC_OUTCOME_NONE);
    }

    if (is_mfc) {
        if (mfc_elig.save)              { labels[n] = "Save";         actions[n++] = NFC_ACT_SAVE; }
        else if (mfc_elig.save_partial) { labels[n] = "Save Partial"; actions[n++] = NFC_ACT_SAVE; }
        if (mfc_elig.find_missing_keys) { labels[n] = "Find Missing Keys"; actions[n++] = NFC_ACT_FIND_KEYS; }
    } else if (!is_st25tb) {
        labels[n] = "Save"; actions[n++] = NFC_ACT_SAVE;
    }
    if (emu == NFC_EMU_UID)           { labels[n] = "Emulate UID"; actions[n++] = NFC_ACT_EMULATE; }
    else if (emu == NFC_EMU_FULL) { labels[n] = "Emulate";     actions[n++] = NFC_ACT_EMULATE; }
    if (nfc_can_unlock(c))                 { labels[n] = "Unlock";      actions[n++] = NFC_ACT_UNLOCK; }
    if (nfc_can_write_ntag21x(c))          { labels[n] = "Write";       actions[n++] = NFC_ACT_WRITE; }
    if (nfc_can_write_mfc(c))              { labels[n] = "Write";       actions[n++] = NFC_ACT_WRITE; }
    /* Dictionary Scan is NOT offered here: the MIFARE Classic key tool is
     * self-contained under NFC > Tools > MIFARE Classic Keys (Dictionary Scan /
     * Key Dictionary). Keeping the read result free of it avoids an ambiguous,
     * duplicated entry point. */
    if (!is_mfc || mfc_elig.info) { labels[n] = "Info"; actions[n++] = NFC_ACT_INFO; }
    return n;
}

/* ---- Retry/More eligibility predicates (m1_nfc.c), verbatim -- gate
 * BOTH the shared footer below and the real button handlers, so the
 * drawn controls and what BACK/CENTER actually do can never disagree. ---- */
static bool nfc_mfc_try_again_allowed(void)
{
    nfc_run_ctx_t *c = nfc_ctx_get();
    if (!c || c->head.family != M1NFC_FAM_CLASSIC) return true;
    const nfc_mfc_info_t *mc = nfc_ctx_get_mfc_info();
    return mfc_action_eligibility(mc ? mc->outcome : MFC_OUTCOME_NONE).try_again;
}

static bool nfc_read_more_menu_has_items(void)
{
    const char *labels[NFC_MENU_MAX_ITEMS];
    uint8_t     actions[NFC_MENU_MAX_ITEMS];
    return nfc_build_action_menu(labels, actions) > 0;
}

/* ---- Capture globals: NOT extracted from m1_nfc.c -- glue this
 * generator adds so the render test can assert on the real show_retry/
 * show_more values the wrapper below actually computed, the same way a
 * production caller would observe them (there is no other seam to read
 * these locals from outside the wrapper). ---- */
bool g_mfc_partial_result_show_retry;
bool g_mfc_partial_result_show_more;

/* ---- Partial/Failed/Cancelled (+ COMPLETE) MFC read-result screen --
 * RESTRUCTURED WRAPPER around statements copied verbatim out of the
 * middle of nfc_read_gui_update() (m1_nfc.c): the MFC family branch
 * immediately followed by the shared bottom-bar footer that
 * unconditionally runs right after it in the real function (section 8a)
 * -- both copied in real source order, so this wrapper now reproduces
 * the exact same statements a real Partial/Failed/Cancelled MFC read
 * result draws, footer included. See this script's own header comment
 * (section 8) for exactly why the MFC block is a restructured slice and
 * what was intentionally left out (nfc_ndef_state() itself). ---- */
static void nfc_mfc_partial_result_draw(void)
{
		u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);

		if (nfc_ctx_get()->head.family == M1NFC_FAM_CLASSIC && nfc_ctx_get_mfc_info()->valid)   // MIFARE Classic (Phase A)
		{
			const nfc_mfc_info_t *mc = nfc_ctx_get_mfc_info();
			nfc_run_ctx_t *cc = nfc_ctx_get();
			char ml[28];

			if (mc->outcome != MFC_OUTCOME_COMPLETE)
			{
				/* Dedicated Partial/Failed/Cancelled result presentation --
				 * COMPLETE (below, unchanged) keeps its exact prior layout;
				 * this increment only adds truthful, distinct wording for
				 * every other outcome, per spec. Actions themselves (Save
				 * Partial / Find Missing Keys / Try Again / Info) are
				 * reached via the existing Retry/More bar below and the
				 * existing action menu -- no new navigation surface. */
				u8g2_SetFont(&m1_u8g2, NFC_FONT_EMPH);
				u8g2_DrawStr(&m1_u8g2, 2, 9,
				    (mc->outcome == MFC_OUTCOME_PARTIAL)   ? "Partial Read" :
				    (mc->outcome == MFC_OUTCOME_FAILED)    ? "Read Failed"  :
				                                             "Cancelled");
				u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);

				if (mc->outcome == MFC_OUTCOME_PARTIAL)
				{
					snprintf(ml, sizeof(ml), "Sectors: %u/%u",
					         (unsigned)mc->sectors_read, (unsigned)mc->sectors_total);
					u8g2_DrawStr(&m1_u8g2, 2, 22, ml);
					snprintf(ml, sizeof(ml), "Keys: %u/%u",
					         (unsigned)mc->keys_found, (unsigned)mc->keys_total);
					u8g2_DrawStr(&m1_u8g2, 2, 33, ml);
				}
				else   // FAILED, or CANCELLED with no data -- mfc_classify_outcome()
				       // already routes a cancelled-with-data result to PARTIAL above
				{
					u8g2_DrawStr(&m1_u8g2, 2, 22, "No sectors recovered");
				}
			}
			else
			{
				u8g2_SetFont(&m1_u8g2, NFC_FONT_EMPH);
				u8g2_DrawStr(&m1_u8g2, 2, 9,
				    (mc->type == M1NFC_MFCTYPE_4K) ? "MIFARE Classic 4K" : "MIFARE Classic 1K");

				u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);
				u8g2_DrawStr(&m1_u8g2, 2, 20, "UID:");
				nfc_draw_hex_cells(26, 20, cc->head.uid, cc->head.uid_len);

				snprintf(ml, sizeof(ml), "Keys found: %u/%u",
				         (unsigned)mc->keys_found, (unsigned)mc->keys_total);
				u8g2_DrawStr(&m1_u8g2, 2, 31, ml);

				snprintf(ml, sizeof(ml), "Sectors read: %u/%u",
				         (unsigned)mc->sectors_read, (unsigned)mc->sectors_total);
				u8g2_DrawStr(&m1_u8g2, 2, 42, ml);
			}
		}

		/* Only draw a control whose handler actually does something: LEFT is a
		 * silent no-op for a COMPLETE/no-data-CANCELLED MFC read
		 * (nfc_mfc_try_again_allowed()), and RIGHT would otherwise open an
		 * empty action menu for a FAILED/no-data-CANCELLED MFC read
		 * (nfc_read_more_menu_has_items()) -- both already gate the real
		 * button handlers above, so the drawn controls and the handlers can
		 * never disagree. Every non-MFC family: both helpers are always
		 * true, so this is visually unchanged. */
		bool show_retry = nfc_mfc_try_again_allowed();
		bool show_more  = nfc_read_more_menu_has_items();

		u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
		u8g2_DrawBox(&m1_u8g2, 0, 52, 128, 12); // Draw an inverted bar at the bottom to display options
		u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_BG); // Write text in inverted color
		u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);   // bottom-bar labels: standard font
		if (show_retry) {
			u8g2_DrawXBMP(&m1_u8g2, 1, 53, 8, 8, arrowleft_8x8); // draw arrowleft icon
			u8g2_DrawStr(&m1_u8g2, 11, 61, "Retry");
		}
		if (show_more) {
			u8g2_DrawXBMP(&m1_u8g2, 119, 53, 8, 8, arrowright_8x8); // draw arrowright icon
			u8g2_DrawStr(&m1_u8g2, 117 - (uint8_t)u8g2_GetStrWidth(&m1_u8g2, "More"), 61, "More");
		}
		if (s_ndef_state == 2 || s_ndef_state == 3)   // readable URL/Text -> centered "View" cue
			u8g2_DrawStr(&m1_u8g2, (uint8_t)((128 - u8g2_GetStrWidth(&m1_u8g2, "View")) / 2), 61, "View");

	/* capture glue (not extracted -- see the globals' own comment above) */
	g_mfc_partial_result_show_retry = show_retry;
	g_mfc_partial_result_show_more  = show_more;
}

/* ---- MFC Info screen -- RESTRUCTURED WRAPPER around statements copied
 * verbatim out of the middle of nfc_info_drawing() (m1_nfc.c). See this
 * script's own header comment (section 8b). ---- */
static void nfc_mfc_partial_info_draw(void)
{
    nfc_run_ctx_t* c = nfc_ctx_get();

    /* ISO15693 / NFC-V: dedicated Info layout (Type, tech, UID, DSFID/AFI,
     * Blocks Read X/Y + block size). Returns before the tech-A ATQA/SAK path. */
    /* MIFARE Classic (Phase A): minimal confirm layout (Type, tech, UID,
     * sector, auth result, blocks read). Returns before the ATQA/SAK path. */
    if (c && c->head.family == M1NFC_FAM_CLASSIC && nfc_ctx_get_mfc_info()->valid)
    {
        const nfc_mfc_info_t *mc = nfc_ctx_get_mfc_info();
        char cline[40];

        u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
        u8g2_FirstPage(&m1_u8g2);
        u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);

        /* Complete read only (mc->outcome == MFC_OUTCOME_COMPLETE): a compact
         * layout that also shows the shared ISO14443A ATQA/SAK fields (the
         * old branch returned before ever reaching those). Partial/failed/
         * cancelled outcomes keep the exact prior layout below, unchanged --
         * this increment does not define a partial-result UI. */
        if (mc->outcome == MFC_OUTCOME_COMPLETE)
        {
            snprintf(cline, sizeof(cline), "MIFARE Classic %s",
                     (mc->type == M1NFC_MFCTYPE_4K) ? "4K" : "1K");
            u8g2_DrawStr(&m1_u8g2, 2, 10, cline);

            u8g2_DrawStr(&m1_u8g2, 2, 21, "UID:");
            if (c->head.uid_len > 0)
                nfc_draw_hex_cells(26, 21, c->head.uid, c->head.uid_len);

            /* Same shared ATQA/SAK convention (label + nfc_draw_hex_cells(),
             * gated on has_atqa/has_sak) as the generic tech-A Info screen
             * further below -- never fabricated when the flags are false. */
            u8g2_DrawStr(&m1_u8g2, 2, 32, "ATQA:");
            if (c->head.a.has_atqa)
                nfc_draw_hex_cells(32, 32, c->head.a.atqa, 2);
            u8g2_DrawStr(&m1_u8g2, 74, 32, "SAK:");
            if (c->head.a.has_sak)
                nfc_draw_hex_cells(98, 32, &c->head.a.sak, 1);

            snprintf(cline, sizeof(cline), "Keys: %u/%u  Sec: %u/%u",
                     (unsigned)mc->keys_found, (unsigned)mc->keys_total,
                     (unsigned)mc->sectors_read, (unsigned)mc->sectors_total);
            u8g2_DrawStr(&m1_u8g2, 2, 43, cline);

            u8g2_DrawStr(&m1_u8g2, 117 - (uint8_t)u8g2_GetStrWidth(&m1_u8g2, "Data"), 61, "Data");
            u8g2_DrawXBMP(&m1_u8g2, 119, 53, 8, 8, arrowright_8x8);

            m1_u8g2_nextpage();
            return;
        }

        /* Partial/Failed/Cancelled-with-data: same MIFARE Classic 1K/4K
         * title logic as the COMPLETE branch above (was previously
         * hardcoded to "1K" regardless of the actual detected type -- the
         * card's real type is already known the instant a card activates,
         * long before the outcome is classified, so this was always a
         * presentation bug, not a missing-data one). */
        snprintf(cline, sizeof(cline), "MIFARE Classic %s",
                 (mc->type == M1NFC_MFCTYPE_4K) ? "4K" : "1K");
        u8g2_DrawStr(&m1_u8g2, 2, 10, cline);

        u8g2_DrawStr(&m1_u8g2, 2, 21, "UID");
        if (c->head.uid_len > 0)
            nfc_draw_hex_cells(23, 21, c->head.uid, c->head.uid_len);

        /* H. Info consistency: every valid MFC result -- Complete or
         * Partial -- shows the same shared identity block (the
         * model: MFC Info always renders ISO14443-3A identity first, then
         * the MFC-specific recovery counts, unconditional on completeness).
         * Same helper, same has_atqa/has_sak gating, same field values as
         * the COMPLETE branch above -- never fabricated when the card
         * genuinely didn't report ATQA/SAK. */
        u8g2_DrawStr(&m1_u8g2, 2, 32, "ATQA:");
        if (c->head.a.has_atqa)
            nfc_draw_hex_cells(32, 32, c->head.a.atqa, 2);
        u8g2_DrawStr(&m1_u8g2, 74, 32, "SAK:");
        if (c->head.a.has_sak)
            nfc_draw_hex_cells(98, 32, &c->head.a.sak, 1);

        /* Two lines, tightened to y=42/y=51 (visual-render gate finding:
         * the original y=43/y=54 placement left "Sectors read: 15/16"
         * overlapping the unchanged "Data" label at y=61; COMPLETE's own
         * single-line "Keys: X/Y  Sec: X/Y" format was tried here too but
         * itself clips past x=128 for realistic two-digit values -- e.g.
         * "Keys: 30/32  Sec: 15/16" measures 137px at NFC_FONT_STD -- so
         * it is not reused here even though COMPLETE keeps it, since
         * COMPLETE's own branch is left untouched per this task's scope).
         * y=42/y=51 matches the 9px inter-row pitch nfc_mfc_dict_progress_draw()
         * already uses safely for this exact pair of lines. */
        snprintf(cline, sizeof(cline), "Keys found: %u/%u",
                 (unsigned)mc->keys_found, (unsigned)mc->keys_total);
        u8g2_DrawStr(&m1_u8g2, 2, 42, cline);

        snprintf(cline, sizeof(cline), "Sectors read: %u/%u",
                 (unsigned)mc->sectors_read, (unsigned)mc->sectors_total);
        u8g2_DrawStr(&m1_u8g2, 2, 51, cline);

        /* "Data >" opens the hex dump (only when something was actually read). */
        if (mc->keys_found > 0U)
        {
            u8g2_DrawStr(&m1_u8g2, 117 - (uint8_t)u8g2_GetStrWidth(&m1_u8g2, "Data"), 61, "Data");
            u8g2_DrawXBMP(&m1_u8g2, 119, 53, 8, 8, arrowright_8x8);
        }

        m1_u8g2_nextpage();
        return;
    }
}

/* ---- m1_gui_submenu_update() (m1_csrc/m1_display.c) + its own file-scope
 * statics/macros, all verbatim ---- */
#define MENU_SCROLLBAR_POS_X				124
#define MENU_SCROLLBAR_POS_Y				0
#define MENU_SCROLLBAR_WIDTH				4

#define MAIN_MENU_TEXT_ITEMS				4
#define MAIN_MENU_TEXT_FRAME_TOP_POS_Y		0
#define MAIN_MENU_TXT_LEFT_POS_X			68
#define MAIN_MENU_TXT_TOP_POS_Y				12
#define MAIN_MENU_TXT_SPACING_VERT			16
#define MAIN_MENU_TEXT_FRAME_H				16
#define MAIN_MENU_TEXT_FRAME_W				75
#define MAIN_MENU_TEXT_FRAME_LEFT_POS_X		48

#define MAIN_MENU_ICON_LEFT_POS_X			50
#define MAIN_MENU_ICON_WIDTH				14
#define MAIN_MENU_ICON_HEIGHT				14

#define MAIN_MENU_LOGO_TOP_POS_Y			24
#define MAIN_MENU_LOGO_LEFT_POS_X			0
#define MAIN_MENU_LOGO_WIDTH				26
#define MAIN_MENU_LOGO_HEIGHT				14

#define MAIN_MENU_LOGO_FONT					M1_MAIN_LOGO_FONT_1B

/* Approved full-width main-menu presentation (main-menu drawing path only;
 * submenu rendering and the shared scrollbar constants are left unchanged). */
#define MAIN_MENU2_ROW_H					16
#define MAIN_MENU2_ICON_LEFT_POS_X			4
#define MAIN_MENU2_TXT_LEFT_POS_X			22
#define MAIN_MENU2_TXT_BASELINE_OFFSET		12
#define MAIN_MENU2_SEL_BAND_LEFT_POS_X		0
#define MAIN_MENU2_SEL_BAND_W				125
#define MAIN_MENU2_POSIND_POS_X				126
#define MAIN_MENU2_POSIND_W					2

#define SUB_MENU_TEXT_ITEMS					4 // rows
#define SUB_MENU_TEXT_FRAME_TOP_POS_Y		0
#define SUB_MENU_TXT_LEFT_POS_X				4
#define SUB_MENU_TEXT_TOP_POS_Y				12
#define SUB_MENU_TEXT_SPACING_VERT			16
#define SUB_MENU_TEXT_FRAME_H				16
#define SUB_MENU_TEXT_FRAME_W				(M1_LCD_DISPLAY_WIDTH - MENU_SCROLLBAR_WIDTH - 1)
#define SUB_MENU_TEXT_FRAME_LEFT_POS_X		0

static const uint8_t menu_window_sizes[] = {MAIN_MENU_TEXT_ITEMS, SUB_MENU_TEXT_ITEMS};
static const uint8_t menu_text_frame_top_pos_y[] = {MAIN_MENU_TEXT_FRAME_TOP_POS_Y, SUB_MENU_TEXT_FRAME_TOP_POS_Y};
static const uint8_t menu_text_left_pos_x[] = {MAIN_MENU_TXT_LEFT_POS_X, SUB_MENU_TXT_LEFT_POS_X};
static const uint8_t menu_text_top_pos_y[] = {MAIN_MENU_TXT_TOP_POS_Y, SUB_MENU_TEXT_TOP_POS_Y};
static const uint8_t menu_text_spacing_vert[] = {MAIN_MENU_TXT_SPACING_VERT, SUB_MENU_TEXT_SPACING_VERT};
static const uint8_t menu_text_frame_h[] = {MAIN_MENU_TEXT_FRAME_H, SUB_MENU_TEXT_FRAME_H};
static const uint8_t menu_text_frame_w[] = {MAIN_MENU_TEXT_FRAME_W, SUB_MENU_TEXT_FRAME_W};
static const uint8_t menu_text_frame_left_pos_x[] = {MAIN_MENU_TEXT_FRAME_LEFT_POS_X, SUB_MENU_TEXT_FRAME_LEFT_POS_X};
static const uint8_t *menu_text_font_n[] = {M1_DISP_MAIN_MENU_FONT_N, M1_DISP_SUB_MENU_FONT_N};
static const uint8_t *menu_text_font_b[] = {M1_DISP_MAIN_MENU_FONT_B, M1_DISP_SUB_MENU_FONT_B};

typedef struct
{
 	uint8_t active_disp_row; // selected row of the display window
	uint8_t disp_top_row; // first row of the moving display window
	uint8_t sel_item; // selected item of the menu list
} S_M1_Disp_Window_t;

static uint8_t disp_window_active_row;
static uint8_t disp_window_top_row; // moving display window
static uint8_t menu_level_id; // main menu (0) or sub menu
static bool info_box_high_box;
static uint8_t info_box_first_row = 0;
static const S_M1_Menu_t *this_gui_menu;


uint8_t m1_gui_submenu_update(const char *phmenu[], uint8_t num_items, uint8_t sel_item, uint8_t direction)
{
	static S_M1_Disp_Window_t x_menu_display[SUB_MENU_LEVEL_MAX];
	static uint8_t x_menu_level = 0, x_menu_update_init = 0;
	uint8_t menu_text_y, menu_frame_y;
	uint8_t disp_window_bottom_row;
	uint8_t n_items, active_item, run;

	n_items = num_items;

	switch ( direction )
	{
		case X_MENU_UPDATE_MOVE_DOWN:
			sel_item = x_menu_display[x_menu_level].sel_item;
			sel_item++;
			if ( sel_item >= n_items )
				sel_item = 0;
			// No break here!

		case MENU_UPDATE_MOVE_DOWN: // moving down
			if ( n_items > menu_window_sizes[menu_level_id] )
			{
				if ( disp_window_active_row < (menu_window_sizes[menu_level_id] - 1) )
				{
					disp_window_active_row++;
				}
				else if ( disp_window_active_row==(menu_window_sizes[menu_level_id] - 1) )
				{
					if ( sel_item==(n_items-1) ) // reach end of the menu items list?
					{
						disp_window_active_row++;
					} // if ( sel_item==(n_items-1) )
					else
					{
						// move display window down
						disp_window_top_row++;
					}
				} // else if ( disp_window_active_row==(menu_window_sizes[menu_level_id] - 1) )
				else // disp_window_active_row==menu_window_sizes[menu_level_id]
				{
					disp_window_active_row = 1; // reset to the first row
					disp_window_top_row = 1;
				} // else
			} // if ( n_items > menu_window_sizes[menu_level_id] )
			else // n_items <= menu_window_sizes[menu_level_id]
			{
				if ( disp_window_active_row < n_items )
				{
					disp_window_active_row++;
				} // if ( disp_window_active_row < n_items )
				else // disp_window_active_row==n_items
				{
					disp_window_active_row = 1; // reset to the first row
				} // else
			} // else
			break;

		case X_MENU_UPDATE_MOVE_UP:
			sel_item = x_menu_display[x_menu_level].sel_item;
			if ( sel_item )
				sel_item--;
			else
				sel_item = n_items - 1;
			// No break here!

		case MENU_UPDATE_MOVE_UP: // moving up
			if ( n_items >= menu_window_sizes[menu_level_id] )
			{
				if ( disp_window_active_row > 2 )
				{
					disp_window_active_row--;
				} // if ( disp_window_active_row > 2 )
				else if ( disp_window_active_row==2 )
				{
					if ( sel_item==0 ) // reach first item of the list?
					{
						disp_window_active_row = 1; // rest to the first row
					} // if ( sel_item==0 )
					else
					{
						// move display window up
						disp_window_top_row--;
					} // else
				} // else if ( disp_window_active_row==2 )
				else // being at the first row
				{
					disp_window_active_row = menu_window_sizes[menu_level_id]; // move to the last row
					disp_window_top_row = n_items - (menu_window_sizes[menu_level_id] - 1);
				} // else
			} // if ( n_items >= menu_window_sizes[menu_level_id] )
			else // n_items < menu_window_sizes[menu_level_id]
			{
				if ( disp_window_active_row > 1 )
				{
					disp_window_active_row--;
				} // if ( disp_window_active_row > 1 )
				else // being at the first row
				{
					disp_window_active_row = n_items; // move to the last item
				} // else
			} // else
			break;

		case MENU_UPDATE_INIT:
		case MENU_UPDATE_RESET:
			disp_window_active_row = 1; // reset to first row
    		disp_window_top_row = 1;
			break;

		case MENU_UPDATE_REFRESH:
			if ( x_menu_update_init )
			{
				x_menu_update_init = 0; // Reset
				x_menu_level = 0;
				disp_window_active_row = x_menu_display[0].active_disp_row; // Restore
				disp_window_top_row = x_menu_display[0].disp_top_row;
			} // if ( x_menu_update_init )
			break;

		case X_MENU_UPDATE_INIT:
			x_menu_update_init = 1; // Mark as initialized
    		x_menu_level = 0; // Reset
			x_menu_display[0].active_disp_row = disp_window_active_row; // back up
			x_menu_display[0].disp_top_row = disp_window_top_row;
			x_menu_display[0].sel_item = 0;
			return 0;

		case X_MENU_UPDATE_RESET:
			x_menu_level++;
			if ( x_menu_level >= SUB_MENU_LEVEL_MAX )
				x_menu_level = SUB_MENU_LEVEL_MAX - 1;
    		disp_window_top_row = 1;
			disp_window_active_row = 1; // reset to first row
    		sel_item = 0; // Overwrite input param
			break;

		case X_MENU_UPDATE_RESTORE:
			if ( x_menu_level )
				x_menu_level--;
			disp_window_active_row = x_menu_display[x_menu_level].active_disp_row; // previous values
			disp_window_top_row = x_menu_display[x_menu_level].disp_top_row;
			sel_item = x_menu_display[x_menu_level].sel_item;
			if ( sel_item >= n_items ) // Restore to an unexpected submenu?
			{
				sel_item = 0;
				disp_window_top_row = 1;
				disp_window_active_row = 1; // Reset to first row
			}
			if ( x_menu_level==0 )
				return 0; // Do nothing if the x_menu stays at its init level
			break;

		case X_MENU_UPDATE_REFRESH:
			sel_item = x_menu_display[x_menu_level].sel_item; // Restore from saved setting
			break;

		case MENU_UPDATE_NONE:
			if ( x_menu_update_init )
			{
				return x_menu_display[x_menu_level].sel_item;
			} // if ( x_menu_update_init )
			break;

		default:
			break;
	} // switch ( direction )

	/* Graphic work starts here */
    u8g2_FirstPage(&m1_u8g2); // This call required for page drawing in mode 1
	u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);

	if ( n_items >= menu_window_sizes[menu_level_id] )
		disp_window_bottom_row = disp_window_top_row + (menu_window_sizes[menu_level_id] - 1); // full window display
	else
		disp_window_bottom_row = disp_window_top_row + (n_items - 1); // partial window display
	active_item = disp_window_top_row;
	active_item += disp_window_active_row - 1;
	menu_frame_y = menu_text_frame_top_pos_y[menu_level_id];
	menu_text_y = menu_text_top_pos_y[menu_level_id];

	if ( menu_level_id == 0 )
	{
		/* ----- Approved full-width scrolling main-menu presentation -----
		 * 8-item scrollable list, 4 visible 16px rows; full-width selection band
		 * with white icon + title; a 2px selection-position indicator on the
		 * right. Consumes the existing scroll state (disp_window_top_row,
		 * disp_window_bottom_row, active_item, sel_item) WITHOUT modifying it.
		 * Submenu rendering (menu_level_id != 0) is left unchanged below. */
		uint8_t mm_row_y = 0;
		for ( run = disp_window_top_row; run <= disp_window_bottom_row; run++ )
		{
			if ( run == active_item )
			{
				/* full-width black selection band; icon + title drawn white */
				u8g2_DrawBox(&m1_u8g2, MAIN_MENU2_SEL_BAND_LEFT_POS_X, mm_row_y, MAIN_MENU2_SEL_BAND_W, MAIN_MENU2_ROW_H);
				u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_BG); // white
				u8g2_DrawXBMP(&m1_u8g2, MAIN_MENU2_ICON_LEFT_POS_X, mm_row_y + 1, MAIN_MENU_ICON_WIDTH, MAIN_MENU_ICON_HEIGHT, this_gui_menu->submenu[run - 1]->icon_ptr);
				u8g2_SetFont(&m1_u8g2, menu_text_font_b[0]);  // selected row: helvB08
				u8g2_DrawStr(&m1_u8g2, MAIN_MENU2_TXT_LEFT_POS_X, mm_row_y + MAIN_MENU2_TXT_BASELINE_OFFSET, phmenu[run - 1]);
				u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT); // restore black
			}
			else
			{
				/* black icon + title on white */
				u8g2_DrawXBMP(&m1_u8g2, MAIN_MENU2_ICON_LEFT_POS_X, mm_row_y + 1, MAIN_MENU_ICON_WIDTH, MAIN_MENU_ICON_HEIGHT, this_gui_menu->submenu[run - 1]->icon_ptr);
				u8g2_SetFont(&m1_u8g2, menu_text_font_n[0]);  // unselected: resoledmedium
				u8g2_DrawStr(&m1_u8g2, MAIN_MENU2_TXT_LEFT_POS_X, mm_row_y + MAIN_MENU2_TXT_BASELINE_OFFSET, phmenu[run - 1]);
			}
			mm_row_y += MAIN_MENU2_ROW_H;
		}

		/* Selection-position indicator: a ~ (64/num_items) px marker placed in one
		 * of num_items discrete positions (top = first item, bottom = last item).
		 * Endpoint-correct; drawn last so the selection band cannot cover it.
		 * Zero/one-item cases guarded before the division. */
		{
			uint8_t mm_mh, mm_my;
			if ( num_items <= 1 )
			{
				mm_mh = M1_LCD_DISPLAY_HEIGHT;
				mm_my = 0;
			}
			else
			{
				mm_mh = M1_LCD_DISPLAY_HEIGHT / num_items;
				if ( mm_mh == 0 )
					mm_mh = 1;
				mm_my = (uint8_t)( ((uint16_t)(M1_LCD_DISPLAY_HEIGHT - mm_mh) * sel_item) / (num_items - 1) );
			}
			u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT);
			u8g2_DrawBox(&m1_u8g2, MAIN_MENU2_POSIND_POS_X, mm_my, MAIN_MENU2_POSIND_W, mm_mh);
		}

		u8g2_NextPage(&m1_u8g2); // Update display RAM

		// Back up (identical to the shared path below)
		if ( x_menu_update_init )
		{
			x_menu_display[x_menu_level].active_disp_row = disp_window_active_row;
			x_menu_display[x_menu_level].disp_top_row = disp_window_top_row;
			x_menu_display[x_menu_level].sel_item = sel_item;
		}
		return 0;
	} // if ( menu_level_id == 0 ) -- new full-width main-menu presentation

	u8g2_SetFont(&m1_u8g2, menu_text_font_n[menu_level_id]);
	for (run=disp_window_top_row; run<=disp_window_bottom_row; run++)
	{
		if ( run==active_item )
		{
			if ( menu_level_id==0 )
			{
		   		// Draw frame for selected menu item
				u8g2_DrawXBMP(&m1_u8g2, menu_text_frame_left_pos_x[menu_level_id], menu_frame_y, menu_text_frame_w[menu_level_id], menu_text_frame_h[menu_level_id], m1_frame_75x16);
			} // if ( menu_level_id==0 )
			else
			{
				u8g2_DrawBox(&m1_u8g2, menu_text_frame_left_pos_x[menu_level_id], menu_frame_y, menu_text_frame_w[menu_level_id], menu_text_frame_h[menu_level_id]);
				u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_BG); // set the color to White
			} // else
			u8g2_SetFont(&m1_u8g2, menu_text_font_b[menu_level_id]);
    		u8g2_DrawStr(&m1_u8g2, menu_text_left_pos_x[menu_level_id], menu_text_y, phmenu[run - 1]);
    		u8g2_SetDrawColor(&m1_u8g2, M1_DISP_DRAW_COLOR_TXT); // return the color to Black
    		u8g2_SetFont(&m1_u8g2, menu_text_font_n[menu_level_id]);
		} // if ( run==active_item )
		else
		{
			u8g2_DrawStr(&m1_u8g2, menu_text_left_pos_x[menu_level_id], menu_text_y, phmenu[run - 1]);
		} // else
		if ( menu_level_id==0 )
		{
			// Draw icons for main menu items
			u8g2_DrawXBMP(&m1_u8g2, MAIN_MENU_ICON_LEFT_POS_X, menu_frame_y + 1, MAIN_MENU_ICON_WIDTH, MAIN_MENU_ICON_HEIGHT, this_gui_menu->submenu[run - 1]->icon_ptr);
		}
		menu_frame_y += menu_text_frame_h[menu_level_id];
		menu_text_y += menu_text_spacing_vert[menu_level_id];
	} // for (run=disp_window_top_row; run<=disp_window_bottom_row; run++)

	if ( menu_level_id==0 )
	{
		// Draw logo for main menu
		u8g2_DrawXBMP(&m1_u8g2, MAIN_MENU_LOGO_LEFT_POS_X, MAIN_MENU_LOGO_TOP_POS_Y, MAIN_MENU_LOGO_WIDTH, MAIN_MENU_LOGO_HEIGHT, m1_logo_26x14);
		u8g2_SetFont(&m1_u8g2, MAIN_MENU_LOGO_FONT);
		u8g2_DrawStr(&m1_u8g2, MAIN_MENU_LOGO_LEFT_POS_X + MAIN_MENU_LOGO_WIDTH + 1, MAIN_MENU_LOGO_TOP_POS_Y + MAIN_MENU_LOGO_HEIGHT, "M1");
	} // if ( menu_level_id==0 )

	// Draw the scroll bar
	u8g2_DrawXBMP(&m1_u8g2, MENU_SCROLLBAR_POS_X, MENU_SCROLLBAR_POS_Y, MENU_SCROLLBAR_WIDTH, M1_LCD_DISPLAY_HEIGHT, menu_scroll_bar_4x64);
	// Draw the scroll bar handle
	u8g2_DrawBox(&m1_u8g2, MENU_SCROLLBAR_POS_X, (M1_LCD_DISPLAY_HEIGHT*sel_item)/num_items, MENU_SCROLLBAR_WIDTH, M1_LCD_DISPLAY_HEIGHT/num_items);

	u8g2_NextPage(&m1_u8g2); // Update display RAM

	// Back up
	if ( x_menu_update_init )
	{
		x_menu_display[x_menu_level].active_disp_row = disp_window_active_row;
		x_menu_display[x_menu_level].disp_top_row = disp_window_top_row;
		x_menu_display[x_menu_level].sel_item = sel_item;
	} // if ( x_menu_update_init )

	return 0;
} // uint8_t m1_gui_submenu_update(const char *phmenu[], uint8_t num_items, uint8_t sel_item, uint8_t direction)

