#!/usr/bin/env python3
"""
extract_wave_builders.py

Pulls each of the five LF wave-builder functions VERBATIM out of the current,
real lfrfid_protocol_*.c files (never hand-retyped, always re-located by
signature against the live file) into FIVE SEPARATE generated .c files, one
per protocol, each compiled as its own translation unit and linked --
deliberately NOT combined into one file, because two of the five real files
(H10301, EM4100) each independently `#define OUTPUT_INVERT`, which would
collide if merged into a single translation unit. AWID/ioProx/Pyramid's own
builders are `static` in the real source; the extracted copies below have
that keyword stripped (nothing else about the body is touched) purely so
each can be an ordinary externally-linked function in its own object file --
this does not change their logic, only how the test links them.

Never modifies the source files; only reads them and writes the generated
files, which are deleted immediately after the test build (see the test
file's own header-comment recipe).
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))


def read(path):
    return open(os.path.join(REPO, path), encoding="utf-8").readlines()


def func_range(buf, sig_substr):
    for i in range(len(buf)):
        if sig_substr in buf[i]:
            depth = 0
            started = False
            for k in range(i, len(buf)):
                for ch in buf[k]:
                    if ch == '{':
                        depth += 1
                        started = True
                    elif ch == '}':
                        depth -= 1
                if started and depth == 0:
                    return i, k
    raise RuntimeError(f"function not found: {sig_substr!r}")


def slice_lines(buf, a, b):
    return "".join(buf[a:b + 1])


def define_block(buf, first_define_substr, last_define_substr):
    i0 = None
    for i, line in enumerate(buf):
        if first_define_substr in line:
            i0 = i
            break
    if i0 is None:
        raise RuntimeError(f"define block start not found: {first_define_substr!r}")
    for i in range(i0, len(buf)):
        if last_define_substr in buf[i]:
            return slice_lines(buf, i0, i)
    raise RuntimeError(f"define block end not found: {last_define_substr!r}")


def strip_leading_static(fn_text):
    return re.sub(r'^static\s+', '', fn_text, count=1)


def single_define(buf, substr):
    """Pull just the one #define line matching substr (e.g. an *_ENCODED_BITS
    constant) -- avoids including the whole real .h, which also declares an
    LFRFIDProtocolBase-typed extern this test has no need of and no
    dependency for."""
    for line in buf:
        if substr in line and line.strip().startswith("#define"):
            return line.rstrip("\n")
    raise RuntimeError(f"#define not found: {substr!r}")


def write_file(path, includes, defines, helper_fn, main_fn):
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "/* GENERATED by extract_wave_builders.py -- DO NOT EDIT.\n"
            " * Every non-comment line below is byte-exact from the current\n"
            " * real source file named in the recipe. */\n"
        )
        for inc in includes:
            if inc.startswith("<"):
                f.write(f"#include {inc}\n")
            else:
                f.write(f"#include \"{inc}\"\n")
        f.write("\n")
        if defines:
            f.write(defines + "\n")
        f.write(helper_fn + "\n")
        f.write(main_fn + "\n")
    print(f"wrote {path}")


# ---- AWID ----
awid = read("lfrfid/lfrfid_protocol_awid.c")
awid_h = read("lfrfid/lfrfid_protocol_awid.h")
awid_defines = (single_define(awid_h, "AWID_ENCODED_BITS") + "\n" +
                define_block(awid, "#define AWID_OUTPUT_INVERT", "#define AWID_EMUL_GPIO_PIN"))
a, b = func_range(awid, "static uint8_t awid_get_bit(const uint8_t *data, size_t position)")
fn_awid_get_bit = slice_lines(awid, a, b)
a, b = func_range(awid, "static int awid_encoded_to_wave(const uint8_t *encoded, uint8_t gpio_pin,")
fn_awid_wave = strip_leading_static(slice_lines(awid, a, b))
write_file(os.path.join(HERE, "lfrfid_awid_wave_extracted.c"),
           ["lfrfid_dma_types.h", "<stddef.h>", "<stdint.h>"],
           awid_defines, fn_awid_get_bit, fn_awid_wave)

# ---- ioProx ----
ioprox = read("lfrfid/lfrfid_protocol_ioprox.c")
ioprox_h = read("lfrfid/lfrfid_protocol_ioprox.h")
ioprox_defines = (single_define(ioprox_h, "IOPROX_ENCODED_BITS") + "\n" +
                  single_define(ioprox, "IOPROX_PULSES_FC8") + "\n" +
                  single_define(ioprox, "IOPROX_PULSES_FC10") + "\n" +
                  define_block(ioprox, "#define IOPROX_EMUL_HALF_ONE_US", "#define IOPROX_EMUL_GPIO_PIN"))
a, b = func_range(ioprox, "static uint8_t ioprox_get_bit(const uint8_t *data, size_t position)")
fn_ioprox_get_bit = slice_lines(ioprox, a, b)
a, b = func_range(ioprox, "static int ioprox_encoded_to_wave(const uint8_t *encoded, uint8_t gpio_pin,")
fn_ioprox_wave = strip_leading_static(slice_lines(ioprox, a, b))
write_file(os.path.join(HERE, "lfrfid_ioprox_wave_extracted.c"),
           ["lfrfid_dma_types.h", "<stddef.h>", "<stdint.h>"],
           ioprox_defines, fn_ioprox_get_bit, fn_ioprox_wave)

# ---- Pyramid ----
pyramid = read("lfrfid/lfrfid_protocol_pyramid.c")
pyramid_h = read("lfrfid/lfrfid_protocol_pyramid.h")
pyr_defines = (single_define(pyramid_h, "PYRAMID_ENCODED_BITS") + "\n" +
               define_block(pyramid, "#define PYR_EMUL_HALF_ONE_US", "#define PYR_EMUL_GPIO_PIN"))
a, b = func_range(pyramid, "static uint8_t pyr_get_bit(const uint8_t *data, size_t position)")
fn_pyr_get_bit = slice_lines(pyramid, a, b)
a, b = func_range(pyramid, "static int pyramid_encoded_to_wave(const uint8_t *encoded, uint8_t gpio_pin,")
fn_pyr_wave = strip_leading_static(slice_lines(pyramid, a, b))
write_file(os.path.join(HERE, "lfrfid_pyramid_wave_extracted.c"),
           ["lfrfid_dma_types.h", "<stddef.h>", "<stdint.h>"],
           pyr_defines, fn_pyr_get_bit, fn_pyr_wave)

# ---- H10301 (already non-static in the real source; extracted anyway so
#      this test never compiles the whole HAL/RTOS-coupled real .c file). ----
h10301 = read("lfrfid/lfrfid_protocol_h10301.c")
h_defines = define_block(h10301, "#define OUTPUT_INVERT", "#define EMUL_PERIOD_ZERO_US")
a, b = func_range(h10301, "static uint8_t get_bit_msb(const uint8_t *buf, int bit_index)")
fn_h_get_bit = slice_lines(h10301, a, b)
a, b = func_range(h10301, "int h10301_raw96_to_wave(const uint8_t raw96[12],")
fn_h_wave = slice_lines(h10301, a, b)
write_file(os.path.join(HERE, "lfrfid_h10301_wave_extracted.c"),
           ["lfrfid_dma_types.h", "<stddef.h>", "<stdint.h>"],
           h_defines, fn_h_get_bit, fn_h_wave)

# ---- EM4100 (already non-static in the real source; extracted anyway so
#      this test never compiles the whole HAL/RTOS-coupled real .c file). ----
em4100 = read("lfrfid/lfrfid_protocol_em4100.c")
e_defines = define_block(em4100, "#define EMUL_EM4100_CORR", "#define OUTPUT_INVERT")
a, b = func_range(em4100, "static uint8_t em4100_frame_get_bit(const uint8_t frame[8], uint16_t bit_index)")
fn_e_get_bit = slice_lines(em4100, a, b)
a, b = func_range(em4100, "uint16_t em4100_build_manchester_wave(")
fn_e_wave = slice_lines(em4100, a, b)
write_file(os.path.join(HERE, "lfrfid_em4100_wave_extracted.c"),
           ["lfrfid_dma_types.h", "<stddef.h>", "<stdint.h>"],
           e_defines, fn_e_get_bit, fn_e_wave)
