/*
 * nfc_desfire_ui_render_test.c
 *
 * Round-4 hardware-rejection proof requested for the DESFire/Clipper transit
 * UI: renders the REAL, UNMODIFIED nfc_desfire_apps_draw() / _files_draw() /
 * _transit_draw() / _data_draw() / _app_detail_draw() / _file_detail_draw()
 * functions from m1_csrc/m1_nfc.c against the REAL u8g2 library (the exact
 * same u8g2_Setup_st7567_enh_dg128064i_f() 128x64 driver setup
 * nfc_desfire_ui_layout_test.c already uses), driven by the REAL
 * nfc_ctx_get()/mf_desfire_parse/nfc_transit_clipper data model, and then
 * inspects the REAL resulting pixel buffer -- not font-metric math, not an
 * illustration.
 *
 * HOW THE REAL, UNMODIFIED DRAW CODE GOT HERE
 * --------------------------------------------
 * m1_csrc/m1_nfc.c is ~7100 lines and, end to end, references on the order
 * of 150 distinct externs from FreeRTOS/CMSIS-RTOS2, the STM32 HAL, and M1's
 * uiView menu framework (menu create/destroy handlers, keypad handlers, MFC
 * raw capture/detect, harvest, T2T unlock, virtual keyboard, file browser,
 * storage, NDEF, RFAL driver/listener/poller glue -- see this session's own
 * symbol census). None of that is reachable from, or needed by, the six
 * drawing functions under test here. Stubbing the whole file's dependency
 * surface to satisfy the compiler for code this test never calls would be a
 * disproportionate, error-prone undertaking unrelated to the actual
 * question (does the real drawing code overlap pixels) -- so instead,
 * NFC/NFC_drv/common/test/stub_desfire_ui/nfc_desfire_ui_draw_extracted.c
 * was generated by extract_desfire_ui.py as a byte-exact, verbatim
 * concatenation of the exact line ranges m1_nfc.c currently uses for the
 * macros, file-scope static nav/scroll state, nfc_desf_draw_str_fit(), and
 * the six draw functions themselves (see that file's own header comment for
 * the exact line numbers). m1_csrc/m1_nfc.c was only ever opened for
 * reading; it was never modified.
 *
 * That generated file is #included directly into THIS translation unit
 * (below), rather than compiled as its own object, specifically so its
 * `static` functions and `static` file-scope selection/scroll variables
 * (s_desf_app_sel, s_desf_apps_scroll, s_desf_sel_app_idx, s_desf_file_sel,
 * s_desf_files_scroll, s_desf_transit_scroll, s_desf_transit_line_count) are
 * directly reachable from this file's test-scenario setup code -- the same
 * "compile it as part of your test binary" technique the task brief
 * suggested, scoped to the relevant slice instead of the whole file.
 *
 * m1_u8g2 (the real firmware's global u8g2_t) and the two real XBM icon
 * arrays the draw functions reference (arrowright_8x8, target_10x10,
 * normally provided by m1_lcd.c / m1_display_data.c) are provided below:
 * m1_u8g2 is a fresh host-side instance (mirroring how
 * nfc_desfire_ui_layout_test.c already does this for its own local `u8g2`),
 * and the two icon arrays are linked from the REAL, unmodified
 * m1_csrc/m1_display_data.c (a genuinely portable, HAL-free data file --
 * `#include <stdint.h>` and nothing else), not re-declared or faked.
 *
 * nfc_ctx_get() and friends come from the REAL nfc_ctx_get() singleton
 * implementation already established by
 * NFC/NFC_drv/common/test/stub_desfire/common/nfc_ctx_stub.c against its
 * sibling nfc_ctx.h -- a structurally-faithful stub of the real
 * NFC/NFC_drv/common/nfc_ctx.h (documented there as unavoidable: the real
 * header pulls in main.h/the full STM32 HAL stack via fields unrelated to
 * DESFire/transit). mf_desfire_deep_t and nfc_transit_result_t underneath
 * it are the REAL, unmodified types from NFC/NFC_drv/common/mf_desfire_parse.h
 * and NFC/NFC_drv/common/nfc_transit_clipper.h, and this test links the
 * REAL, unmodified .c files implementing them (both genuinely portable,
 * HAL-free C).
 *
 * PIXEL COLLISION METHOD (why two renders per screen, not one)
 * --------------------------------------------------------------
 * u8g2's framebuffer is a 1-bit-per-pixel bitmap. The header is drawn first
 * and identically in every scenario of a given screen (0 items, N items,
 * box selected or plain text) -- so a naive "are both renders 'on' at the
 * same pixel" scan across a fixed rectangle is trivially satisfied by the
 * header's OWN pixels regardless of whether anything actually invades its
 * space, and a hardcoded rectangle goes stale the moment the box geometry
 * changes (exactly what happened here mid-fix: the first geometry
 * correction attempt passed this stale check while a real 1-row touch
 * against the header still existed, caught only by re-deriving the
 * comparison from first principles instead of trusting an old literal).
 *
 * The real invariant: the header's own measured ink rows (HEADER_Y0..
 * HEADER_Y1 below) must render byte-for-byte IDENTICALLY no matter what the
 * rest of the screen draws. So, per screen, this test renders the REAL,
 * unmodified draw function TWICE -- once with app_count==0 (Apps) /
 * file_count==0 (Files), which still executes the exact same unconditional
 * header-drawing statements before taking its early-return fallback-text
 * path, and once with the real scenario under test (a selection box at row
 * 0, plain unselected text at row 0, or a scrolled-off row 0) -- and
 * requires header_row_diff_scan() to find ZERO differing pixels across the
 * full display width within HEADER_Y0..HEADER_Y1. Any difference proves
 * something other than the header painted into the header's own rows.
 *
 * This works uniformly whether row 0 holds a selection box, plain
 * unselected text, or (once scrolled) neither -- there is no special-cased
 * "no box, skip the check" branch, since a plain label bleeding upward into
 * the header is just as real a defect as a box doing so.
 *
 * Build (from repo root, macOS host):
 *   python3 <scratch>/extract_desfire_ui.py   # regenerate the verbatim slice
 *   cc -std=c11 -Wall -Wextra \
 *     -I Drivers/u8g2_csrc \
 *     -I NFC/NFC_drv/common/test/stub_desfire/common \
 *     -I NFC/NFC_drv/common \
 *     -I NFC/NFC_drv/common/test/stub_desfire_ui \
 *     NFC/NFC_drv/common/test/nfc_desfire_ui_render_test.c \
 *     NFC/NFC_drv/common/mf_desfire_parse.c \
 *     NFC/NFC_drv/common/nfc_transit_clipper.c \
 *     NFC/NFC_drv/common/test/stub_desfire/common/nfc_ctx_stub.c \
 *     m1_csrc/m1_display_data.c \
 *     $(find Drivers/u8g2_csrc -maxdepth 1 -name 'u8g2_*.c' ! -name 'u8g2_fonts.c') \
 *     Drivers/u8g2_csrc/u8x8_*.c \
 *     -o /tmp/nfc_desfire_ui_render_test -lm && /tmp/nfc_desfire_ui_render_test
 *   (the glob now excludes u8g2_fonts.c -- the ~38 MB full upstream font
 *   catalog, no longer part of the normal build -- and instead relies on
 *   u8g2_csrc/u8g2_fonts_selected.c, the byte-exact generated extraction
 *   of only the 13 fonts this firmware actually links; see
 *   Drivers/u8g2_csrc/tools/extract_selected_fonts.py. Compiling both
 *   files together would fail with duplicate-symbol link errors.)
 *
 * Output: one .ppm (P6, 4x nearest-neighbor upscaled for viewability) per
 * test-matrix scenario, written to OUT_DIR below, plus the real pass/fail
 * assertion output on stdout.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "u8g2.h"
#include "mf_desfire_parse.h"
#include "nfc_transit_clipper.h"
#include "nfc_ctx.h"

#ifndef OUT_DIR
#define OUT_DIR "/tmp/desfire_framebuffers"
#endif

#define DISP_W 128
#define DISP_H 64

/* ---- globals the extracted code expects (normally m1_lcd.c / m1_display_data.c) ---- */
u8g2_t m1_u8g2;
extern const uint8_t arrowright_8x8[];  /* REAL bitmap, from the REAL m1_csrc/m1_display_data.c */
extern const uint8_t target_10x10[];    /* REAL bitmap, from the REAL m1_csrc/m1_display_data.c */

/* ---- the REAL, verbatim-extracted draw functions + their exact static
 * state, pulled into THIS translation unit (see the file banner above and
 * the generated file's own header comment for why). ---- */
#include "stub_desfire_ui/nfc_desfire_ui_draw_extracted.c"

/*============================ pass/fail bookkeeping =================================*/
static int g_pass = 0, g_fail = 0;
#define CHECK(c, m) do { if (c) g_pass++; else { g_fail++; printf("  FAIL: %s (line %d)\n", (m), __LINE__); } } while (0)

/*============================ real pixel readback ====================================*/
/* u8g2_ll_hvline_vertical_top_lsb's own layout (Drivers/u8g2_csrc/u8g2_ll_hvline.c):
 * bytes are vertical, LSB = top pixel of each 8-row band; byte offset for
 * (x,y) is (y>>3)*tile_width*8 + x, bit index (y&7). Read directly out of
 * the REAL u8g2 tile buffer -- not re-derived/estimated. */
static int get_pixel(u8g2_t *u, int x, int y)
{
    if (x < 0 || x >= DISP_W || y < 0 || y >= DISP_H) return 0;
    uint8_t *buf = u8g2_GetBufferPtr(u);
    int tile_width = (int)u8g2_GetBufferTileWidth(u);
    int band = y >> 3;
    long byte_off = (long)band * tile_width * 8 + x;
    int bit = y & 7;
    return (buf[byte_off] >> bit) & 1;
}

static void render(void (*draw_fn)(void))
{
    u8g2_ClearBuffer(&m1_u8g2);
    u8g2_FirstPage(&m1_u8g2);
    do {
        draw_fn();
    } while (u8g2_NextPage(&m1_u8g2));
}

static void snapshot(uint8_t grid[DISP_H][DISP_W])
{
    for (int y = 0; y < DISP_H; y++)
        for (int x = 0; x < DISP_W; x++)
            grid[y][x] = (uint8_t)get_pixel(&m1_u8g2, x, y);
}

/* Writes a 4x nearest-neighbor upscaled P6 (binary PPM) of the CURRENT real
 * u8g2 buffer. "on" pixel (TXT color, lit) -> black; "off" -> white --
 * matches how the physical reflective LCD's dark-on-light text reads. */
static void dump_ppm(const char *name)
{
    char path[512];
    snprintf(path, sizeof(path), "%s/%s.ppm", OUT_DIR, name);
    FILE *f = fopen(path, "wb");
    if (!f) { fprintf(stderr, "could not open %s for writing\n", path); return; }
    const int scale = 4;
    fprintf(f, "P6\n%d %d\n255\n", DISP_W * scale, DISP_H * scale);
    for (int y = 0; y < DISP_H; y++) {
        unsigned char row[DISP_W * scale * 3];
        for (int x = 0; x < DISP_W; x++) {
            int on = get_pixel(&m1_u8g2, x, y);
            unsigned char v = on ? 0 : 255;
            for (int sx = 0; sx < scale; sx++) {
                row[(x * scale + sx) * 3 + 0] = v;
                row[(x * scale + sx) * 3 + 1] = v;
                row[(x * scale + sx) * 3 + 2] = v;
            }
        }
        for (int sy = 0; sy < scale; sy++)
            fwrite(row, 1, sizeof(row), f);
    }
    fclose(f);
    printf("  wrote %s\n", path);
}

/*============================ header-row integrity check ==============================*/
/* Why equality, not "both on": u8g2's framebuffer is 1-bit, so once
 * something is drawn "on" you cannot tell from the final bitmap alone
 * whether that bit came from the header or from something drawn over/near
 * it -- a naive "are both header_grid and row0_grid 'on' here" scan is
 * trivially satisfied by the header's OWN pixels, since the header is drawn
 * identically, first, in every scenario of this screen (with 0 items, with
 * N items, box or no box) -- it would "collide with itself" regardless of
 * whether the real bug is fixed. A hardcoded box rectangle is no better: it
 * goes stale the moment the box geometry changes, and it can accidentally
 * include unrelated content (the app_count==0 scenario also draws a
 * fallback "No applications"/"Auth required..." message below the header,
 * which is not sharable across an app_count==0 vs N>0 comparison).
 *
 * The real invariant that must hold is: HEADER_Y0..HEADER_Y1 (the header's
 * own measured ink rows -- ascent 8 + descent 2 for NFC_FONT_EMPH at
 * baseline 9, i.e. rows 1..11; row 0 included for margin) must be rendered
 * IDENTICALLY regardless of what the rest of the screen draws. So: render
 * once with items (real selection box or plain row-0 text engaged) and
 * once with zero items (pure header + fallback text, which never reaches
 * this row range), then require the two renders' pixels to be PIXEL-EQUAL
 * across HEADER_Y0..HEADER_Y1, full display width. Any difference there
 * proves something other than the header painted into the header's own
 * rows -- which is exactly what the original, hardware-reported bug did
 * (the old row-0 box extended up into rows 3..13, overlapping row 1..11). */
#define HEADER_Y0 0
#define HEADER_Y1 11

static int header_row_diff_scan(uint8_t header_grid[DISP_H][DISP_W], uint8_t row0_grid[DISP_H][DISP_W],
                                 int coords_out[][2], int max_coords)
{
    int n = 0;
    for (int y = HEADER_Y0; y <= HEADER_Y1; y++) {
        for (int x = 0; x < DISP_W; x++) {
            if (header_grid[y][x] != row0_grid[y][x]) {
                if (n < max_coords) { coords_out[n][0] = x; coords_out[n][1] = y; }
                n++;
            }
        }
    }
    return n;
}

/*============================ scenario builders =======================================*/

static void setup_apps_scenario(uint8_t app_count, uint8_t sel, uint8_t scroll)
{
    nfc_ctx_clear_desfire();
    nfc_run_ctx_t *ctx = nfc_ctx_get();
    mf_desfire_deep_t *deep = &ctx->desfire_deep;
    deep->app_count = app_count;
    deep->apps_protected = false;
    for (uint8_t i = 0; i < app_count && i < MF_DESFIRE_DEEP_MAX_APPS; i++) {
        deep->apps[i].id.id[0] = (uint8_t)(0x10 + i);
        deep->apps[i].id.id[1] = (uint8_t)(0x2A + i);
        deep->apps[i].id.id[2] = (uint8_t)(0xF0 + i);
        deep->apps[i].select_ok = (i != 1); /* one "(no select)" app to exercise that text path */
    }
    s_desf_app_sel = sel;
    s_desf_apps_scroll = scroll;
}

static const mf_desfire_file_type_t k_file_types[] = {
    MfDesfireFileTypeStandard, MfDesfireFileTypeBackup, MfDesfireFileTypeValue,
    MfDesfireFileTypeLinearRecord, MfDesfireFileTypeCyclicRecord,
    MfDesfireFileTypeTransactionMac, MfDesfireFileTypeUnknown,
};
static const mf_desfire_file_read_status_t k_file_stats[] = {
    MfDesfireFileComplete, MfDesfireFilePartial, MfDesfireFileProtected,
    MfDesfireFileUnsupported, MfDesfireFileFailed, MfDesfireFileNotAttempted,
};

static void setup_files_scenario(uint8_t file_count, uint8_t sel, uint8_t scroll)
{
    nfc_ctx_clear_desfire();
    nfc_run_ctx_t *ctx = nfc_ctx_get();
    mf_desfire_deep_t *deep = &ctx->desfire_deep;
    deep->app_count = 1;
    deep->apps[0].select_ok = true;
    deep->apps[0].file_count = file_count;
    for (uint8_t i = 0; i < file_count && i < MF_DESFIRE_MAX_FILES_PER_APP; i++) {
        mf_desfire_file_t *file = &deep->apps[0].files[i];
        file->id = i;
        file->settings_valid = true;
        file->settings.type = k_file_types[i % (sizeof(k_file_types)/sizeof(k_file_types[0]))];
        file->read_status = k_file_stats[i % (sizeof(k_file_stats)/sizeof(k_file_stats[0]))];
    }
    s_desf_sel_app_idx = 0;
    s_desf_file_sel = sel;
    s_desf_files_scroll = scroll;
}

static void setup_transit_scenario(void)
{
    nfc_ctx_clear_desfire();
    nfc_run_ctx_t *ctx = nfc_ctx_get();
    nfc_transit_result_t *t = &ctx->transit;

    t->card_id = NfcTransitCardClipper;
    t->card_type_label = "Card";
    t->serial_valid = true;  t->serial_number = 4294967295UL;      /* uint32 max, worst-case width */
    t->balance_valid = true; t->balance_cents = -32768;            /* int16 min -> "$-327.68" worst case */
    t->last_update_valid = true; t->last_update_1900 = 3944000000UL; /* real non-"Never" date */
    t->last_terminal_valid = true; t->last_terminal_id = 0xFFFF;   /* worst-case width */
    t->last_txn_valid = true; t->last_txn_id = 65535;              /* uint16 max, worst-case width */
    t->counter_valid = true; t->counter = 65535;                   /* uint16 max, worst-case width */

    t->ride_count = 2;
    t->rides_truncated = false;
    /* Ride 1: worst-case AGENCY name ("SF Bay Ferry", the longest entry in
     * s_agency_names[]), no zone table for this agency -> "Unknown". */
    t->rides[0].agency_id = 0x001B;
    t->rides[0].fare_cents = 675;
    t->rides[0].vehicle_id = 0;
    t->rides[0].has_time_on = true;  t->rides[0].time_on_1900 = 3944000100UL;
    t->rides[0].has_time_off = false; t->rides[0].time_off_1900 = 0;
    t->rides[0].zone_on_id = 0x0099;   /* not in any zone table -> "Unknown" */
    t->rides[0].zone_off_id = 0;

    /* Ride 2: worst-case ZONE name ("Pleasant Hill/Contra Costa Centre", the
     * longest entry in any *_zones[] table), agency BART (0x0004), plus
     * max-width vehicle id and max-negative fare. */
    t->rides[1].agency_id = 0x0004;
    t->rides[1].fare_cents = -32768;
    t->rides[1].vehicle_id = 65535;
    t->rides[1].has_time_on = true;  t->rides[1].time_on_1900 = 3944005000UL;
    t->rides[1].has_time_off = true; t->rides[1].time_off_1900 = 3944009000UL;
    t->rides[1].zone_on_id = 0x0013;
    t->rides[1].zone_off_id = 0x0013;

    /* Force a mid-scroll position (this screen has far more lines than fit
     * on one page with two ride records + all header fields). */
    s_desf_transit_scroll = 6;
}

static void setup_filedetail_scenario_standard(void)
{
    nfc_ctx_clear_desfire();
    nfc_run_ctx_t *ctx = nfc_ctx_get();
    mf_desfire_deep_t *deep = &ctx->desfire_deep;
    deep->app_count = 1;
    deep->apps[0].select_ok = true;
    deep->apps[0].file_count = 1;
    mf_desfire_file_t *file = &deep->apps[0].files[0];
    file->id = 0x01;
    file->settings_valid = true;
    file->settings.type = MfDesfireFileTypeStandard;
    file->settings.comm = MfDesfireCommPlaintext;
    file->settings.access_rights = 0xE000;
    file->settings.size = 32;
    file->read_status = MfDesfireFileComplete;
    file->data_len = 32;
    for (int i = 0; i < 32; i++) file->data[i] = (uint8_t)(0xA0 + i);
    s_desf_sel_app_idx = 0;
    s_desf_file_sel = 0;
    s_desf_filedetail_scroll = 0;
}

static void setup_filedetail_scenario_value(void)
{
    nfc_ctx_clear_desfire();
    nfc_run_ctx_t *ctx = nfc_ctx_get();
    mf_desfire_deep_t *deep = &ctx->desfire_deep;
    deep->app_count = 1;
    deep->apps[0].select_ok = true;
    deep->apps[0].file_count = 1;
    mf_desfire_file_t *file = &deep->apps[0].files[0];
    file->id = 0x02;
    file->settings_valid = true;
    file->settings.type = MfDesfireFileTypeValue;
    file->settings.comm = MfDesfireCommEnciphered;
    file->settings.access_rights = 0x1234;
    file->settings.value_lo_limit = -32768;
    file->settings.value_hi_limit = 32767;
    file->read_status = MfDesfireFileProtected;   /* Value files hold no dumpable bytes here -- Protected, matching a real enciphered-comm file */
    file->data_len = 0;
    s_desf_sel_app_idx = 0;
    s_desf_file_sel = 0;
    s_desf_filedetail_scroll = 0;
}

/*============================ collision reporting =====================================*/
/* Works uniformly whether row 0 holds the selection box or plain unselected
 * text -- header_row_diff_scan() only asks "did the header's own rows
 * change from the pure-header reference render", which is a meaningful,
 * non-trivial question in both cases (a plain row-0 label bleeding upward
 * into the header would fail this exactly as a box would). */
static void report_and_check_header_integrity(const char *screen_name,
                                               uint8_t header_grid[DISP_H][DISP_W], uint8_t row0_grid[DISP_H][DISP_W])
{
    int coords[512][2];
    int n = header_row_diff_scan(header_grid, row0_grid, coords, 512);
    if (n == 0) {
        printf("  [%s] real-render scan: header rows (y=%d..%d) rendered IDENTICALLY to the "
               "pure-header reference -- no interference.\n", screen_name, HEADER_Y0, HEADER_Y1);
    } else {
        printf("  [%s] real-render scan: %d pixel(s) in the header's own rows (y=%d..%d) differ "
               "from the pure-header reference render:", screen_name, n, HEADER_Y0, HEADER_Y1);
        int shown = n < 512 ? n : 512;
        for (int i = 0; i < shown; i++) printf(" (%d,%d)", coords[i][0], coords[i][1]);
        printf("\n");
    }
    char msg[160];
    snprintf(msg, sizeof(msg),
             "%s: header rows (y=%d..%d) must render identically regardless of row-0 content "
             "(box or plain text)", screen_name, HEADER_Y0, HEADER_Y1);
    CHECK(n == 0, msg);
}

/*============================ test-matrix scenarios ====================================*/

int main(void)
{
    u8g2_Setup_st7567_enh_dg128064i_f(&m1_u8g2, U8G2_R0, u8x8_dummy_cb, u8x8_dummy_cb);
    u8g2_InitDisplay(&m1_u8g2);
    u8g2_SetPowerSave(&m1_u8g2, 0);

    static uint8_t header_grid[DISP_H][DISP_W];
    static uint8_t row0_grid[DISP_H][DISP_W];

    printf("== 1. Applications: 1 app, row 0 selected ==\n");
    setup_apps_scenario(1, 0, 0);
    render(nfc_desfire_apps_draw);
    dump_ppm("01_apps_1app_row0_selected");
    snapshot(row0_grid);
    setup_apps_scenario(0, 0, 0);
    render(nfc_desfire_apps_draw);
    dump_ppm("01_apps_header_only_AUX");
    snapshot(header_grid);
    report_and_check_header_integrity("Applications (1 app)", header_grid, row0_grid);

    printf("== 2. Applications: 4 apps, first selected ==\n");
    setup_apps_scenario(4, 0, 0);
    render(nfc_desfire_apps_draw);
    dump_ppm("02_apps_4apps_first_selected");
    snapshot(row0_grid);
    report_and_check_header_integrity("Applications (4 apps, first selected)", header_grid, row0_grid);

    printf("== 3. Applications: 4 apps, middle (idx 2) selected ==\n");
    setup_apps_scenario(0, 0, 0); /* refresh the header-only footprint under THIS screen's exact header text ("Applications") */
    render(nfc_desfire_apps_draw);
    snapshot(header_grid);
    setup_apps_scenario(4, 2, 0); /* fits on one screen (4 <= NFC_DESF_LIST_VISIBLE_ROWS==4), no scroll */
    render(nfc_desfire_apps_draw);
    dump_ppm("03_apps_4apps_middle_selected");
    snapshot(row0_grid);
    report_and_check_header_integrity("Applications (4 apps, middle selected)", header_grid, row0_grid);

    printf("== 4. Applications: 4 apps, last selected ==\n");
    setup_apps_scenario(4, 3, 0);
    render(nfc_desfire_apps_draw);
    dump_ppm("04_apps_4apps_last_selected");
    snapshot(row0_grid);
    report_and_check_header_integrity("Applications (4 apps, last selected)", header_grid, row0_grid);

    printf("== 5. Files: 1 file, selected ==\n");
    setup_files_scenario(1, 0, 0);
    render(nfc_desfire_files_draw);
    dump_ppm("05_files_1file_selected");
    snapshot(row0_grid);
    setup_files_scenario(0, 0, 0);
    render(nfc_desfire_files_draw);
    dump_ppm("05_files_header_only_AUX");
    snapshot(header_grid);
    report_and_check_header_integrity("Files (1 file)", header_grid, row0_grid);

    printf("== 6. Files: 32 files, first selected ==\n");
    setup_files_scenario(32, 0, 0);
    render(nfc_desfire_files_draw);
    dump_ppm("06_files_32files_first_selected");
    snapshot(row0_grid);
    report_and_check_header_integrity("Files (32 files, first selected)", header_grid, row0_grid);

    printf("== 7. Files: 32 files, middle selected (scrolled) ==\n");
    setup_files_scenario(0, 0, 0);  /* refresh header-only footprint under THIS screen's exact header text ("Files") */
    render(nfc_desfire_files_draw);
    snapshot(header_grid);
    setup_files_scenario(32, 16, 13); /* scroll = sel - VISIBLE_ROWS(4) + 1, matching the real kp_move rule */
    render(nfc_desfire_files_draw);
    dump_ppm("07_files_32files_middle_selected_scrolled");
    snapshot(row0_grid);
    report_and_check_header_integrity("Files (32 files, middle selected, scrolled)", header_grid, row0_grid);

    printf("== 8. Files: 32 files, last selected (scrolled) ==\n");
    setup_files_scenario(32, 31, 28); /* max_start = 32-4 = 28 */
    render(nfc_desfire_files_draw);
    dump_ppm("08_files_32files_last_selected_scrolled");
    snapshot(row0_grid);
    report_and_check_header_integrity("Files (32 files, last selected, scrolled)", header_grid, row0_grid);

    printf("== 9. Transit/Clipper summary: full realistic data set, forced scroll ==\n");
    setup_transit_scenario();
    render(nfc_desfire_transit_draw);
    dump_ppm("09_transit_clipper_full_scrolled");
    CHECK(s_desf_transit_line_count > NFC_DESF_LIST_VISIBLE_ROWS,
          "Transit screen: real line count exceeds one screen's visible rows (scrolling is genuinely exercised)");

    printf("== 10a. File detail: Standard file ==\n");
    setup_filedetail_scenario_standard();
    render(nfc_desfire_file_detail_draw);
    dump_ppm("10a_filedetail_standard");

    printf("== 10b. File detail: Value file ==\n");
    setup_filedetail_scenario_value();
    render(nfc_desfire_file_detail_draw);
    dump_ppm("10b_filedetail_value");

    printf("== 11. DESFire Summary: realistic EV1 4K card, 1 app/8 files (matches the round-4 hardware photo comparison) ==\n");
    {
        nfc_ctx_clear_desfire();
        nfc_run_ctx_t *ctx = nfc_ctx_get();
        uint8_t v[28] = {0};
        v[3] = 0x01; /* hw_major = EV1 */
        v[5] = 0x18; /* hw_storage = 4K */
        v[12] = 0x18; /* sw_storage = 4K -> bytes_total = 1<<(0x18>>1) = 4096, no '+' (even) */
        v[14]=0x04; v[15]=0x1F; v[16]=0x66; v[17]=0xD2; v[18]=0xDA; v[19]=0x78; v[20]=0x80; /* real card UID */
        ctx->desfire.present = true;
        memcpy(ctx->desfire.v, v, sizeof(v));
        ctx->desfire_deep.app_count = 1;
        ctx->desfire_deep.apps[0].key_settings_valid = true;
        ctx->desfire_deep.apps[0].key_settings.free_directory_list = true;
        ctx->desfire_deep.apps[0].file_count = 8;
        ctx->desfire_deep.free_memory_valid = true;
        ctx->desfire_deep.free_memory_bytes = 2016; /* representative displayed free-memory value */
    }
    render(nfc_desfire_summary_draw);
    dump_ppm("11_desfire_summary_ev1_4k");
    {
        /* This screen uses the same full-width solid footer bar as
         * nfc_desfire_apps_draw()/files_draw() (rows 52-63, unconditionally
         * overwritten after body content is drawn) rather than the
         * narrower "corner hint" style a first attempt used -- that first
         * attempt reserved only the icon's column gutter and a real render
         * (right here) caught it still colliding with the "More" TEXT
         * label, which sits further left than the icon. The bar removes
         * that whole class of failure structurally, so the meaningful
         * check is simply that the bar is actually present where expected:
         * row 52, column 0 must be "on" (the box's own top-left corner) --
         * proving the footer draws at all, not that some later refactor
         * silently dropped it. */
        CHECK(get_pixel(&m1_u8g2, 0, 52) != 0, "DESFire Summary: footer bar is present at its expected top-left corner");
    }

    printf("== 11b. DESFire Summary: same realistic card, scrolled to the UID/app-count/bytes lines ==\n");
    /* Round-4's real bug: at the OLD fixed-baseline layout, every one of
     * these lines truncated with ".." at this exact card's real values
     * ("UID: 04 1F 66 D2 DA..", "1 Application, 8 Fi..", "4096 bytes, 2016
     * by.."). s_desf_summary_scroll=2 brings the UID line to the top row so
     * this render actually exercises them (row 0 alone only shows the
     * device-name/tech lines, which were never the truncated ones). */
    s_desf_summary_scroll = 2;
    render(nfc_desfire_summary_draw);
    dump_ppm("11b_desfire_summary_ev1_4k_scrolled_uid_counts_bytes");
    s_desf_summary_scroll = 6;
    render(nfc_desfire_summary_draw);
    dump_ppm("11c_desfire_summary_ev1_4k_scrolled_counts_bytes");
    s_desf_summary_scroll = 7;
    render(nfc_desfire_summary_draw);
    dump_ppm("11d_desfire_summary_ev1_4k_scrolled_bytes_free");
    s_desf_summary_scroll = 0;

    /* Automated truncation guard, not just a visual dump: measure the REAL
     * production-font width (u8g2_GetStrWidth) of every content line this
     * exact scenario produces, against the same 118px budget
     * nfc_desf_draw_str_fit() enforces. This is exactly the check that
     * would have caught the original round-4 bug ("Tech: ISO 14443-4
     * (NFC-A)", "UID: 04 1F 66 D2 DA 78 80", "1 Application, 8 Files",
     * "4096 bytes, 2016 bytes free" all measured over budget) without
     * requiring a human to eyeball a PPM. If a future edit reintroduces an
     * over-budget line, this fails loudly instead of silently truncating. */
    {
        u8g2_SetFont(&m1_u8g2, NFC_FONT_STD);
        const char *content_lines[] = {
            "EV1 4K", "Tech: ISO 14443-4", "(NFC-A)", "UID:",
            "04 1F 66 D2", "DA 78 80",
            "1 Application,", "8 Files",
            "4096 bytes total", "2016 bytes free",
        };
        for (size_t i = 0; i < sizeof(content_lines) / sizeof(content_lines[0]); i++) {
            uint8_t w = u8g2_GetStrWidth(&m1_u8g2, content_lines[i]);
            char msg[96];
            snprintf(msg, sizeof(msg), "DESFire Summary line \"%s\" (%upx) fits the 118px budget, not truncated",
                      content_lines[i], (unsigned)w);
            CHECK(w <= 118, msg);
        }
    }

    printf("== 12. DESFire Summary: auth-required-to-read-apps case ==\n");
    {
        nfc_ctx_clear_desfire();
        nfc_run_ctx_t *ctx = nfc_ctx_get();
        uint8_t v[28] = {0};
        v[3] = 0x12; v[5] = 0x1E; v[12] = 0x1E; /* EV2, 32K -- different card, exercises the type/size table's other branches */
        ctx->desfire.present = true;
        memcpy(ctx->desfire.v, v, sizeof(v));
        ctx->desfire_deep.apps_protected = true;
    }
    render(nfc_desfire_summary_draw);
    dump_ppm("12_desfire_summary_auth_required");

    /* Bonus: DESFire Data (GetVersion) and Application Detail screens, for
     * completeness (not part of the header/row0 collision question, which
     * the task scoped to Applications/Files specifically, but still real,
     * unmodified rendered output worth capturing since these two functions
     * were extracted and linked anyway). */
    printf("== bonus: nfc_desfire_data_draw (GetVersion) ==\n");
    {
        nfc_ctx_clear_desfire();
        nfc_run_ctx_t *ctx = nfc_ctx_get();
        uint8_t v[28];
        for (int i = 0; i < 28; i++) v[i] = (uint8_t)(0x10 + i);
        ctx->desfire.present = true;
        memcpy(ctx->desfire.v, v, sizeof(v));
        s_desf_scroll = 0;
    }
    render(nfc_desfire_data_draw);
    dump_ppm("bonus_desfire_data_getversion");

    printf("== bonus: nfc_desfire_app_detail_draw ==\n");
    setup_apps_scenario(2, 0, 0);
    {
        nfc_run_ctx_t *ctx = nfc_ctx_get();
        ctx->desfire_deep.apps[0].key_settings_valid = true;
        ctx->desfire_deep.apps[0].key_settings.max_keys = 5;
        ctx->desfire_deep.apps[0].key_settings.free_directory_list = true;
        ctx->desfire_deep.apps[0].key_version_count = 3;
        ctx->desfire_deep.apps[0].file_count = 4;
    }
    s_desf_sel_app_idx = 0;
    render(nfc_desfire_app_detail_draw);
    dump_ppm("bonus_desfire_app_detail");

    printf("\nnfc_desfire_ui_render_test: %d passed, %d failed\n", g_pass, g_fail);
    return (g_fail == 0) ? 0 : 1;
}
